baseUrl=https://www.saucedemo.com/
browser=chrome
validUsername=standard_user
validPassword=secret_sauce
invalidUsername=locked_out_user
invalidPassword=wrong_password
firstName=Saddam
lastName=Tester
postalCode=500001